# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='contraindication',
        ),
        migrations.AddField(
            model_name='post',
            name='mode_of_application',
            field=models.TextField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='release_form',
            field=models.CharField(default=200, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='shelf_life',
            field=models.TextField(default=200),
            preserve_default=False,
        ),
    ]
