# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190107_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mode_of_application',
            new_name='Способ_применения',
        ),
        migrations.AddField(
            model_name='post',
            name='availability',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
    ]
