# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190107_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='availability',
            new_name='Наличие',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='contraindication',
            new_name='Противопоказания',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='shelf_life',
            new_name='Срок_годности',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='release_form',
            new_name='Форма_выпуска',
        ),
    ]
