# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190107_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Название',
        ),
    ]
