# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190107_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Наличие',
            field=models.CharField(max_length=20),
        ),
    ]
