# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190107_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Противопоказания',
            new_name='Противопоказания_к_применению',
        ),
    ]
