# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_противопоказания_к_применению'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Противопоказания',
            field=models.TextField(default='Противопоказания к применению: '),
            preserve_default=False,
        ),
    ]
