# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_противопоказания'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Форма_выпуска',
            field=models.TextField(),
        ),
    ]
