# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190107_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Способ_применения',
        ),
    ]
