# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_способ_применения'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Способ_применения',
            field=models.TextField(default='Способ применения: '),
            preserve_default=False,
        ),
    ]
