# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_способ_применения'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Форма_выпуска',
        ),
    ]
