# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_форма_выпуска'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Срок_годности',
        ),
    ]
