# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_срок_годности'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Срок_годности',
            field=models.CharField(default='Срок годности: 12 месяцев', max_length=20),
            preserve_default=False,
        ),
    ]
