# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_срок_годности'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Наличие',
        ),
    ]
