# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_post_наличие'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Наличие',
            field=models.CharField(default='Наличие на складе: ', max_length=20),
            preserve_default=False,
        ),
    ]
