# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190107_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Лекарство',
        ),
    ]
