# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190107_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Лекарство',
            new_name='Medicine',
        ),
    ]
