# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20190107_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Выдача',
            field=models.CharField(default='Выдача осуществляется ', max_length=100),
            preserve_default=False,
        ),
    ]
