# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_vitamins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vitamins',
            new_name='Vitamin',
        ),
    ]
