# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190107_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitamin',
            name='Название',
            field=models.TextField(),
        ),
    ]
