# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20190107_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitamin',
            name='Вкус',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vitamin',
            name='Название',
            field=models.CharField(max_length=200),
        ),
    ]
