# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20190107_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitamin',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vitamin',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitamin',
            name='Наличие',
            field=models.CharField(default='Наличие на складе: ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitamin',
            name='Противопоказания',
            field=models.CharField(default='Противопоказания к применению: ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitamin',
            name='Способ_применения',
            field=models.TextField(default='Способ применения: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitamin',
            name='Срок_годности',
            field=models.CharField(default='Срок годности: ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitamin',
            name='Форма_выпуска',
            field=models.TextField(default='Форма выпуска: '),
            preserve_default=False,
        ),
    ]
