# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Ваш_email',
            new_name='Ваш_email_или_номер_телефона',
        ),
        migrations.AlterField(
            model_name='request',
            name='Форма_выпуска',
            field=models.CharField(max_length=200),
        ),
    ]
