# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20190108_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitamin',
            name='author',
        ),
        migrations.DeleteModel(
            name='Vitamin',
        ),
    ]
